{{- if (.Values.secret).enabled }}
{{- range $nameSuffix, $data := .Values.secret.files }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "application.name" $ }}-{{ $nameSuffix }}
  namespace: {{ template "application.namespace" $ }}
  labels:
    {{- include "application.labels" $ | nindent 4 }}
    {{- if $.Values.secret.additionalLabels }}
    {{ toYaml $.Values.secret.additionalLabels | nindent 4 }}
    {{- end }}
  {{- if $data.annotations }}
  annotations:
    {{ toYaml $data.annotations | nindent 4 }}
  {{- else if $.Values.secret.annotations }}
  annotations:
    {{ toYaml $.Values.secret.annotations | nindent 4 }}
  {{- end }}
type: Opaque
  {{- if $data.data }}
data:
  {{- range $key, $value := $data.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
  {{- if $data.encodedData }}
  {{ toYaml $data.encodedData | nindent 2 }}
  {{- end }}
  {{- if $data.stringData }}
stringData:
  {{ toYaml $data.stringData | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
